pub const ACTIONS: [&str; 76] = [
    "amuses",
    "avoids",
    "berates",
    "boggles",
    "bothers",
    "buries",
    "catches",
    "commands",
    "contaminates",
    "controls",
    "converts",
    "delivers",
    "destroys",
    "disfigures",
    "eats",
    "enters",
    "fondles",
    "handles",
    "harasses",
    "hassles",
    "helps",
    "imitates",
    "infiltrates",
    "inherits",
    "joins",
    "kills",
    "leaves",
    "massages",
    "molests",
    "persuades",
    "perverts",
    "pitches",
    "rebuilds",
    "reinforces",
    "removes",
    "replaces",
    "resurrects",
    "saves",
    "serves",
    "spanks",
    "squeezes",
    "strokes",
    "subverts",
    "swallows",
    "swats",
    "torments",
    "tortures",
    "transforms",
    "whips",
    "teases",
    "stomps",
    "mates with",
    "tickles",
    "audits",
    "beats",
    "defeats",
    "outwits",
    "manipulates",
    "defects to",
    "titillates",
    "perverts",
    "defenestrates",
    "discards",
    "abandons",
    "talks to",
    "talks back to",
    "allies with",
    "discovers",
    "betrays",
    "assassinates",
    "promotes",
    "pretends to be",
    "disguises",
    "disobeys",
    "alters",
    "intimidates",
];
