pub const INTROS: [&str; 34] = [
    "4 out of 5 dentists recommend that",
    "Abort immediately unless",
    "Abort previous sequence.",
    "Advance code sequence.",
    "Alert all stations!",
    "Confirmed report:",
    "Contrary to popular belief,",
    "Delete all evidence that",
    "Determine whether",
    "E.F. Hutton says",
    "Effective immediately,",
    "Enemy agents now know that",
    "Fnord!",
    "Follow plan x if",
    "Ignore previous message.",
    "Ignore this message.",
    "Imperative that",
    "It appears that",
    "It is not true that",
    "Most people surveyed believe that",
    "Observe and report if",
    "Oral Roberts dreamed that",
    "Our foes believe that",
    "Our reporters claim that",
    "Pentagon officials deny that",
    "Please investigate report that",
    "Step up operation.",
    "Terminate operation if",
    "The surgeon general warns that",
    "Unsubstantiated rumor:",
    "Urgent!",
    "Usual sources confirm that",
    "Warning!",
    "We suspect that",
];
