pub const NAMES: [&str; 148] = [
    "007",
    "a dead relative",
    "a long-lost uncle",
    "a dead rock star",
    "Abdul Al-Azrad",
    "Abraham Lincoln",
    "Bill Gates",
    "Albert Einstein",
    "Ali Baba",
    "Aladdin",
    "Batman",
    "Buck Rogers",
    "Bullwinkle",
    "Captain Ahab",
    "Captain America",
    "Captain Kirk",
    "Captain Nemo",
    "Charlie Brown",
    "Cthulhu",
    "Dilbert",
    "Darth Vader",
    "Dave Letterman",
    "Uncle Bob",
    "Dracula",
    "Elvis",
    "Erik Bloodaxe",
    "Evil Stevie",
    "Fearless Leader",
    "Flaming Carrot",
    "George Lucas",
    "Gerald Ford",
    "Gandhi",
    "Grandmother",
    "Gumby",
    "Hamlet",
    "Han Solo",
    "Hitler",
    "Hulk Hogan",
    "Hunter S. Thompson",
    "Internal Security",
    "Isaac Asimov",
    "Jack the Ripper",
    "Jimmy Carter",
    "Johnny-B-Gud",
    "Joseph Stalin",
    "King Arthur",
    "King Tut",
    "Lex Luthor",
    "Luke Skywalker",
    "Michael Jordan",
    "Mick Jagger",
    "Mr. Bill",
    "Mr. Ed",
    "Mr. Science",
    "Mr. Spock",
    "Nelson Mandela",
    "Nixon",
    "Norman Bates",
    "Obi-Wan Kenobi",
    "Oliver North",
    "Paul Newman",
    "Perry Mason",
    "Princess Leia",
    "Rambo",
    "Ringo",
    "Robby the Robot",
    "Robert Heinlein",
    "Rocky",
    "Roger Rabbit",
    "Ronald Reagan",
    "Scrooge",
    "Sir Lancelot",
    "Snoopy",
    "Spiderman",
    "Squad 23",
    "Steve",
    "Steven Spielberg",
    "Superman",
    "the A.C.L.U.",
    "The Computer",
    "the Discordian",
    "Sir Paul",
    "the Hand",
    "The Illuminati",
    "the Joker",
    "the Legion of Doom",
    "the ninja",
    "the Secret Master",
    "the Secret Service",
    "the vice squad",
    "Thor",
    "Tiny Tim",
    "Tweety-Bird",
    "Uncle Duke",
    "Weird Al",
    "Winston Churchill",
    "yo' mama",
    "your brother",
    "your evil twin",
    "your father",
    "your mother",
    "your sister",
    "Zaphod Beeblebrox",
    "Zeus",
    "Zonker",
    "Donovan's Brain",
    "Jimmy Hoffa",
    "Tristero",
    "the Archdean",
    "Asmodeus",
    "Archangel Gabriel",
    "Al-Qaeda",
    "Angel",
    "Arnold Schwarzenegger",
    "Barry Bonds",
    "Bill Clinton",
    "Bill O'Reilly",
    "Britney Spears",
    "Bud Selig",
    "Buffy",
    "Captain Archer",
    "Condoleeza Rice",
    "Dick Cheney",
    "Harry Potter",
    "Harvey Birdman",
    "Hillary Clinton",
    "Jacques Chirac",
    "Jay Leno",
    "Joe Montana",
    "John Ashcroft",
    "Jon Stewart",
    "Karl Rove",
    "LeBron James",
    "Neo",
    "Osama bin-Laden",
    "Peter Jackson",
    "President Bartlett",
    "President Bush",
    "Saddam Hussein",
    "Sponge Bob Square Pants",
    "T'Pol",
    "Tony Blair",
    "the American Idol",
    "the Bachelor",
    "the Bachelorette",
    "the Crocodile Hunter",
    "the Dixie Chicks",
    "the Powerpuff Girls",
];
