//! Array of nouns representing objects, creatures, and concepts.

/// Contains 192 nouns that can be used as subjects or objects in
/// generated fantasy orders, including weapons, magical items, creatures, and abstract concepts.
///
/// # Examples
///
/// Some nouns include: "sword", "dragon", "treasure", "amulet"
pub const NOUNS: [&str; 192] = [
    "911 file",
    "(censored)",
    "amethyst",
    "amulet",
    "ash tray",
    "baby",
    "BBS",
    "beer bottle",
    "blueprint",
    "boat",
    "book",
    "bowling ball",
    "business card",
    "button",
    "cable",
    "cactus",
    "cannibal",
    "capsule",
    "carnation",
    "cash",
    "cat",
    "cauliflower",
    "chainsaw",
    "chair",
    "chicken",
    "club",
    "cockroach",
    "code wheel",
    "coke can",
    "compact disc",
    "computer",
    "cork",
    "couch",
    "cow",
    "crystal",
    "cummerbund",
    "cyberdeck",
    "demon",
    "devil",
    "diamond",
    "dictaphone",
    "dictator",
    "dinosaur",
    "disk drive",
    "document",
    "dragon",
    "drug",
    "duck",
    "elephant",
    "engine",
    "eye",
    "file",
    "flag",
    "floppy disk",
    "fly",
    "football",
    "frame",
    "frog",
    "geographer",
    "goldfish",
    "grasshopper",
    "grimoire",
    "gyroslugger",
    "hammer",
    "hat",
    "hat-rack",
    "helmet",
    "hemisphere",
    "hot tub",
    "hypodermic",
    "ice cream",
    "ID card",
    "iguana",
    "implement",
    "infant",
    "insect",
    "jellybean",
    "jet",
    "jet ski",
    "jukebox",
    "kitten",
    "Klingon",
    "krugerrand",
    "kumquat",
    "lamp",
    "light bulb",
    "machine gun",
    "mallet",
    "manuscript",
    "mason jar",
    "message",
    "mosquito",
    "motorcycle",
    "mouse",
    "oar",
    "octopus",
    "olive",
    "ostrich",
    "paddle",
    "paintbrush",
    "paper clip",
    "passport",
    "password file",
    "password",
    "pendant",
    "penguin",
    "petunia",
    "phased plasma rifle",
    "phone",
    "photocopy",
    "piranha",
    "pistol",
    "pit viper",
    "plant",
    "playtester",
    "pop tart",
    "power drill",
    "ptarmigan",
    "pterodactyl",
    "puppy",
    "pyramid",
    "racquetball",
    "radio",
    "railroad",
    "razor",
    "rescuer",
    "ring",
    "rom chip",
    "saber",
    "saxophone",
    "scenario",
    "scraper",
    "screwdriver",
    "scuba mask",
    "sculpture",
    "sex toy",
    "shark",
    "shoggoth",
    "skateboard",
    "ski lift",
    "skillet",
    "spark plug",
    "spider",
    "submarine",
    "surfboard",
    "sword",
    "teddy bear",
    "telegram",
    "television",
    "tennis ball",
    "termite",
    "textbook",
    "toast",
    "tornado",
    "traitor",
    "transmitter",
    "treasure chest",
    "tree",
    "trolley",
    "trumpet",
    "typewriter",
    "user's manual",
    "Uzi",
    "van",
    "virus",
    "volleyball",
    "wand",
    "wheel",
    "whip",
    "yak",
    "Zulu",
    "INWO deck",
    "ukelele",
    "icon",
    "amphibian",
    "toad",
    "terminal",
    "additive",
    "piccolo",
    "tuba",
    "angel",
    "demon",
    "CD-ROM",
    "DVD",
    "Deep One",
    "Handheld",
    "MP3",
    "Segway",
    "dog",
    "iMac",
    "laptop",
    "nanite",
];
