//! Array of location names and geographical features.

/// Contains place names including fantasy locations, real places,
/// and fictional settings that can serve as destinations or origins in generated orders.
///
/// # Examples
///
/// Some places include: "the dungeon", "Mordor", "the ancient castle"
pub const PLACES: &[&str] = &[
    "(not available at your clearance)",
    "Afghanistan",
    "Alpha Centauri",
    "Alpha Complex",
    "Atlantis",
    "Austin",
    "Baghdad",
    "Berkeley",
    "Berlin",
    "Buckingham Palace",
    "Callahan's Place",
    "Cheyenne Mountain",
    "Chicago",
    "Cyberworld",
    "Dallas",
    "Death Valley",
    "Dime Box",
    "Endsville",
    "Gasoline Alley",
    "Gotham City",
    "headquarters",
    "Hell",
    "Hollywood",
    "Hong Kong",
    "Iran",
    "Iraq",
    "Israel",
    "Joe's Bar and Grill",
    "Kabul",
    "Katmandu",
    "Lake Geneva",
    "Las Vegas",
    "left field",
    "Lithuania",
    "London",
    "Los Angeles",
    "Main Street",
    "Mars",
    "Middle-earth",
    "Mission Control",
    "Mordor",
    "Moscow",
    "Munich",
    "my back yard",
    "Peking",
    "Poland",
    "San Francisco",
    "Siberia",
    "Sixth Street",
    "SJ Games",
    "Switzerland",
    "Tel Aviv",
    "the back forty",
    "the Bastille",
    "the bathroom",
    "the best place possible",
    "the brewery",
    "the Bat Cave",
    "the corner bar",
    "the dentists' convention",
    "the doghouse",
    "the dumpster",
    "the editorial department",
    "the Empire State Building",
    "the hackers' convention",
    "the home of a trusted friend",
    "the Hotel California",
    "the Last National Bank",
    "the North Pole",
    "the ocean",
    "the outback",
    "the Phoenix Project",
    "the river",
    "the same place as before",
    "the service station",
    "the South Pole",
    "the Super Bowl",
    "the tavern",
    "the toxic waste dump",
    "the U.S. Attorney's Office",
    "the Vatican",
    "the Watergate Hotel",
    "the White House",
    "Toledo",
    "Topeka",
    "Uranus",
    "Wall Street",
    "you-know-where",
    "your place",
    "Yrth",
    "the Death Star",
    "beautiful downtown Burbank",
    "Smallville",
    "the Shire",
];
