//! Array of prepositions and prepositional phrases for spatial and temporal relationships.

/// Contains 102 prepositions and prepositional phrases that establish relationships
/// between characters, objects, and places in generated fantasy orders.
///
/// # Examples
///
/// Some prepositions include: "goes to", "flees from", "takes refuge in"
pub const PREPOSITIONS: [&str; 102] = [
    "assumes responsibility for",
    "avoids servants of",
    "deals with",
    "elopes with",
    "evades agents of",
    "flees from",
    "flees to",
    "flies to",
    "flies toward",
    "goes for",
    "goes to",
    "has finished in",
    "has left with",
    "hides in",
    "is attacked by",
    "is commanded by",
    "is concerned about",
    "is contaminated by",
    "is destroyed by",
    "is distressed by",
    "is financed by",
    "is fondled by",
    "is found by",
    "is imitated by",
    "is infiltrated by",
    "is joined by",
    "is like a god to",
    "is removed by",
    "is the patron of",
    "is threatened by",
    "listens to",
    "makes fun of",
    "may not visit",
    "moves to",
    "originates from",
    "reports to",
    "retreats from",
    "returns to",
    "shoots henchmen of",
    "should watch for",
    "steals from",
    "takes blame for",
    "takes control of",
    "takes no notice of",
    "takes refuge in",
    "travels to",
    "walks to",
    "was eliminated by",
    "was seen in",
    "will go to",
    "withdraws from",
    "assumed responsibility for",
    "avoided servants of",
    "has dealt with",
    "eloped with",
    "evaded agents of",
    "fled from",
    "fled to",
    "flew to",
    "flew toward",
    "has gone for",
    "went to",
    "hides in",
    "was attacked by",
    "was commanded by",
    "was concerned about",
    "was contaminated by",
    "was destroyed by",
    "was distressed by",
    "was financed by",
    "was fondled by",
    "was found by",
    "was imitated by",
    "was infiltrated by",
    "was joined by",
    "was removed by",
    "was the patron of",
    "was threatened by",
    "listened to",
    "made fun of",
    "moved to",
    "originated from",
    "reported to",
    "retreated from",
    "returned to",
    "shot henchmen of",
    "watched for",
    "stole from",
    "took blame for",
    "took control of",
    "took no notice of",
    "took refuge in",
    "traveled to",
    "walked to",
    "withdrew from",
    "plays with",
    "played with",
    "is assassinated by",
    "was assassinated by",
    "is boggled by",
    "was boggled by",
    "performs surgical alternations on",
];
